apiVersion: v1
kind: Service
metadata:
  name: connectedproducts-service
  labels:
    app: connectedproducts
    tier: connectedproducts
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  # type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 4012
    nodePort: 31003
  selector:
    app: connectedproducts
    tier: connectedproducts
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: connectedproducts
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: iot4ishieldengine
  #   tier: iot4i
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 2
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: iot4ishieldengine
  #     tier: iot4i
  template:
    metadata:
      labels:
        app: connectedproducts
        tier: connectedproducts
    spec:
      containers:
      - name: connectedproducts
        image: registry.eu-gb.bluemix.net/alexisrs/connectedproducts
        ports:
        - containerPort: 4012